title: Treasury ERAP Guidance
email: matthew.j.dingee@omb.eop.gov
baseurl: "/"

styles: styles.min.css

url: "https://smeqa.usds.gov" # the base hostname & protocol for your site, e.g. http://example.com
author: U.S. Digital Service

repository: usds/erap-guidance

github_url: https://github.com/usds/erap-guidance/
github: [metadata]

# Build settings
markdown: kramdown

# Assets settings
# sass:
#   sass_dir: assets/stylesheets/
#  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

last-modified-at:
  date-format: '%B %d, %Y'

# Jekyll SEO Tag
# See https://github.com/jekyll/jekyll-seo-tag
logo: /img/usds-logo-onwhite.png

# Google Analytics - Gov wide account
# analytics_id: "UA-132706295-1"

collections:
  faqs:
    sort_by: sort_number

# Exclude from processing.
exclude:
  - ".ruby-version"
  - ".sass-cache"
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - config
  - js
  - vendor
  - manifest.yml
  - node_modules
  - package.json
  - gulpfile.js
  - circle.yml
  - css
  - compressing.sh
  - package-lock.json
